name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HOST }}/ts3video:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_HOST }}/ts3video:latest
